# Usar Nginx para servir los archivos estáticos
FROM nginx:alpine

# Copiar los archivos de tu carpeta actual al directorio de Nginx
COPY . /usr/share/nginx/html

# Exponer el puerto 80
EXPOSE 80